USE AdventureWorks2022;

DECLARE @personID INT = 999;
DECLARE @title VARCHAR(10);

SELECT @title = Title FROM Person.Person
WHERE BusinessEntityID = @personID;

IF @title = 'Mr.'
	PRINT 'HELLO SIR!';
ELSE IF @title = 'Ms.'
	PRINT 'HELLO MA`AM';
ELSE IF @title IS NULL
	PRINT 'NO TITLE FPUND FOR THIS PERSON';

GO
--PRODUCT DELIVERY TIME
DECLARE @SalesOrderID INT = 43660;
DECLARE @OrderDate DATE;
DECLARE @DayOld INT;

--SETTING THE ORDER DATE FROM THE ADVW TABLE
SELECT @OrderDate = OrderDate FROM Sales.SalesOrderHeader
WHERE SalesOrderID = @SalesOrderID;

--GETTING DATE DIFFERENCE
SET @DayOld = DATEDIFF(DAY, @OrderDate, '2011-05-31 00:00:00.00')

IF @DayOld <= 7
	PRINT 'RECENT ORDER WITHIN THE LAST 7 DAYS';
ELSE IF @DayOld <= 30
	PRINT 'THIS ORDER IS WITHIN THE LAST MONTH';
ELSE IF @DayOld <= 365
	PRINT 'THIS ORDER IS WITHIN THIS YEAR';
ELSE IF @DayOld > 365
	PRINT 'THIS ORDER IS MORE THAN A YEAR OLD';

SELECT OrderDate FROM Sales.SalesOrderHeader;